### ISSUE TITLE
SFML Issues Warm Up/Moving On/Start the Game

### ISSUE THREAD

**Issue by edutools-service** [jetbrains-academy/CppBasics#11]
After running `brew install sfml` and running CMake Rebuild, I got errors regarding arm64 vs amd64. In order to resolve this, I had to run `brew install cmake` and then update the CMake Settings under `Preferences` to use just `cmake` instead of the bundled version.
ld: warning: ignoring file /usr/local/lib/libsfml-audio.2.6.0.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/lib/libsfml-graphics.2.6.0.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/lib/libsfml-system.2.6.0.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
ld: warning: ignoring file /usr/local/lib/libsfml-window.2.6.0.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture arm64:
  "sf::WindowBase::pollEvent(sf::Event&)", referenced from:
      processInput(sf::RenderWindow&) in main.cpp.o
  "sf::CircleShape::setRadius(float)", referenced from:
      initPlayer(sf::CircleShape&, sf::Texture&) in main.cpp.o
  "sf::CircleShape::CircleShape(float, unsigned long)", referenced from:
      _main in main.cpp.o
  "sf::RenderStates::Default", referenced from:
      render(sf::RenderWindow&, sf::Sprite const&, sf::Shape const&) in main.cpp.o

**Comment by boruno** [comment]
It seems that the problem has been solved on the SFML side (the library has been updated for ARM processors), since it is currently not reproducible.
